name: Deploy to EC2

on:
  push:
   branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
      - name: Add SSH known hosts 
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets. }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets. }} 
          ' cd /var/www/html && git pull origin main '
