name: Deploy to EC2

on:
  push:
   branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
      - name: Add SSH known hosts 
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -tt ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }} << 'EOF' 
           sudo -i
           echo "Navigating to project directory..."
           cd /home/ec2-user/GithubAcitonsRepository
           echo "Pulling latest changes from GitHub..."
           git pull origin main 
          EOF
